name: deploy myblog

on: 
  push:
    branches:
      - 'main' # 针对 main 分支
    paths:
      - '.github/workflows/*'
      - 'src/**'
      - 'bin/*'
      - 'package.json'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2 #第三方的 action

      - name: set id_rsa # 设置 id_rsa
        run: |
          mkdir -p ~/.ssh/
          echo "${{secrets.MY_ID_RSA}}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan 106.15.41.62 >> ~/.ssh/known_hosts

      - name: deploy # 部署
        run: |
          ssh root@106.15.41.62 "
          # 进入项目目录
          cd /root/myblog/server
          git checkout .
          git checkout main
          git pull

          # 重启服务
          npm install
          npm run prd
          "

      - name: delete id_rsa # 删除 id_rsa
        run: rm -rf ~/.ssh/id_rsa