name: deploy myblog

on: 
  push:
    branches:
      - 'main' # 针对 main 分支
    paths:
      - '.github/workflows/*'
      - 'src/**'
      - 'bin/*'
      - 'package.json'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2 #第三方的 action

      - name: crate a folder # 创建文件夹
        run: mkdir test-folder

      - name: print id_rsa # 打印id
        run: echo ${{ secrets.MY_ID_RSA }}
        
      - name: create a file # 创建文件
        run: |
         cd test-folder
         touch a.txt
         echo "hello world" > a.txt
         cat a.txt

      - name: delete a file # 删除文件
        run: rm -rf a.txt

